export const TEST_TLS_CA_KEY = `
-----BEGIN EC PARAMETERS-----
BggqhkjOPQMBBw==
-----END EC PARAMETERS-----
-----BEGIN EC PRIVATE TEST KEY-----
MHcCAQEEIG4HAczfWZebejQ6dgaby5eQKI1D4a5QiXqdZjSfhXHqoAoGCCqGSM49
AwEHoUQDQgAECSAa9aRTu5bC3j4i2xMQdU7svqKV75CmLxjjSCp8714NMSXuZPcs
drgOod/0eebemYdJsYh/5M5RNqzdFpOEtA==
-----END EC PRIVATE TEST KEY-----
`.replace(/TEST KEY/g, "KEY");

export const TEST_TLS_CA_CERT = `
-----BEGIN TEST CERTIFICATE-----
MIIBgjCCASegAwIBAgIUG2TJHaSiWGt5U8u7KVFG+l3wClAwCgYIKoZIzj0EAwIw
FTETMBEGA1UEAwwKZGVtZXJnaTpDQTAgFw02OTEyMzEyMzAwMDBaGA8yOTY5MDUw
MjIzMDAwMFowFTETMBEGA1UEAwwKZGVtZXJnaTpDQTBZMBMGByqGSM49AgEGCCqG
SM49AwEHA0IABAkgGvWkU7uWwt4+ItsTEHVO7L6ile+Qpi8Y40gqfO9eDTEl7mT3
LHa4DqHf9Hnm3pmHSbGIf+TOUTas3RaThLSjUzBRMB0GA1UdDgQWBBQ+gZhdJ0ll
CCmUSo/XNNsoBzCngDAfBgNVHSMEGDAWgBQ+gZhdJ0llCCmUSo/XNNsoBzCngDAP
BgNVHRMBAf8EBTADAQH/MAoGCCqGSM49BAMCA0kAMEYCIQDfFgwnnIiBnAriD2x+
btOSRtdTWUN3h1HrVUapyZUmqAIhALgcjLXWBkYzGnph1uKMWW5vLZ8ahZI9mjbJ
GUZCRYEC
-----END TEST CERTIFICATE-----
`.replace(/TEST CERTIFICATE/g, "CERTIFICATE");

export const TEST_TLS_SERVER_KEY = `
-----BEGIN EC PARAMETERS-----
BggqhkjOPQMBBw==
-----END EC PARAMETERS-----
-----BEGIN EC PRIVATE TEST KEY-----
MHcCAQEEIP5XjxgCyFgF1wne8YxKsk7SJQ72pvA8nOH4+inC+cQaoAoGCCqGSM49
AwEHoUQDQgAEcb/1vTFF8cxIKw7T5L7PzYDFdpAdGgRe3cvOjK4TZ/O9U3GbFLdt
Cu9d8SjOlyEjrCSSNg2AeBzf5XKzzJcDEw==
-----END EC PRIVATE TEST KEY-----
`.replace(/TEST KEY/g, "KEY");

export const TEST_TLS_SERVER_CERT = `
-----BEGIN TEST CERTIFICATE-----
MIIBqzCCAVGgAwIBAgIUaFUtmGfYMOnxHw1z70jp7FQUCNUwCgYIKoZIzj0EAwIw
FTETMBEGA1UEAwwKZGVtZXJnaTpDQTAgFw02OTEyMzEyMzAwMDBaGA8yOTY5MDUw
MjIzMDAwMFowGTEXMBUGA1UEAwwOZGVtZXJnaTpTZXJ2ZXIwWTATBgcqhkjOPQIB
BggqhkjOPQMBBwNCAARxv/W9MUXxzEgrDtPkvs/NgMV2kB0aBF7dy86MrhNn871T
cZsUt20K713xKM6XISOsJJI2DYB4HN/lcrPMlwMTo3kwdzA1BgNVHREELjAsggdk
ZW1lcmdpgglsb2NhbGhvc3SHBH8AAAGHEAAAAAAAAAAAAAAAAAAAAAEwHQYDVR0O
BBYEFCbufvRX7W0RjPxNyprd4hPH8yN0MB8GA1UdIwQYMBaAFD6BmF0nSWUIKZRK
j9c02ygHMKeAMAoGCCqGSM49BAMCA0gAMEUCIQCRxljpBb7ZxTg5OQrEbTx2UdVG
Bfjk2DM2ldkdxJMtlQIgHXycUHgDaDXGtiVr2DPmz1mTu3ZuUWD/e/a3rvY4t0o=
-----END TEST CERTIFICATE-----
`.replace(/TEST CERTIFICATE/g, "CERTIFICATE");

export const TEST_TLS_SERVER_EXPIRED_CERT = `
-----BEGIN TEST CERTIFICATE-----
MIIBqTCCAU+gAwIBAgIUaFUtmGfYMOnxHw1z70jp7FQUCNcwCgYIKoZIzj0EAwIw
FTETMBEGA1UEAwwKZGVtZXJnaTpDQTAeFw02OTEyMzEyMzAwMDBaFw03MDAxMDEy
MzAwMDBaMBkxFzAVBgNVBAMMDmRlbWVyZ2k6U2VydmVyMFkwEwYHKoZIzj0CAQYI
KoZIzj0DAQcDQgAEcb/1vTFF8cxIKw7T5L7PzYDFdpAdGgRe3cvOjK4TZ/O9U3Gb
FLdtCu9d8SjOlyEjrCSSNg2AeBzf5XKzzJcDE6N5MHcwNQYDVR0RBC4wLIIHZGVt
ZXJnaYIJbG9jYWxob3N0hwR/AAABhxAAAAAAAAAAAAAAAAAAAAABMB0GA1UdDgQW
BBQm7n70V+1tEYz8Tcqa3eITx/MjdDAfBgNVHSMEGDAWgBQ+gZhdJ0llCCmUSo/X
NNsoBzCngDAKBggqhkjOPQQDAgNIADBFAiBaDs8aJ6ADPRrVxucFIBn8C+Y9sqRd
V4iJKKV08a7ZOwIhAIQxeaKYLPEEnx1HMwceQYkZlj9gB1UgH8UNLeDKCKwE
-----END TEST CERTIFICATE-----
`.replace(/TEST CERTIFICATE/g, "CERTIFICATE");

export const TEST_TLS_SERVER_INVALID_CERT = `
-----BEGIN TEST CERTIFICATE-----
MIIBqzCCAVGgAwIBAgIUB0Vkwh5/MjFsZbJ7o94fYBRaeOcwCgYIKoZIzj0EAwIw
FTETMBEGA1UEAwwKZGVtZXJnaTpDQTAgFw02OTEyMzEyMzAwMDBaGA8yOTY5MDUw
MjIzMDAwMFowGTEXMBUGA1UEAwwOZGVtZXJnaTpTZXJ2ZXIwWTATBgcqhkjOPQIB
BggqhkjOPQMBBwNCAARi6QedRNZSop//Zdvp6MU7AP1SbRMnLcI4o4tCXDbE+FH4
Jdh8GNbmCPg98ETegRr9dDIQybYxVV+6m1+95bfno3kwdzA1BgNVHREELjAsggdk
ZW1lcmdpgglsb2NhbGhvc3SHBH8AAAGHEAAAAAAAAAAAAAAAAAAAAAEwHQYDVR0O
BBYEFD7QMfW5ougSMx5JncP7as7MO2nIMB8GA1UdIwQYMBaAFAXDewnOPHuTkEcy
yWBztSM8qzZuMAoGCCqGSM49BAMCA0gAMEUCIQDTwhAbmF+2BJKlbDoyjcFmJiBJ
zd3RPy9F2DLLhQXIgAIgXkplQ/RjnQoRK8iwIqhILDMVGLFnruvSbAgMFBTpRlI=
-----END TEST CERTIFICATE-----
`.replace(/TEST CERTIFICATE/g, "CERTIFICATE");

export const TEST_TLS_CLIENT_KEY = `
-----BEGIN EC PARAMETERS-----
BggqhkjOPQMBBw==
-----END EC PARAMETERS-----
-----BEGIN EC PRIVATE TEST KEY-----
MHcCAQEEIBiHXJapmMcCOQ9NM0G7kfmgXgxJb4PkQ/LLlPs1i5bgoAoGCCqGSM49
AwEHoUQDQgAEMz02cCg/tlHI1QP2M73IQ9aaNLA3hxnqYMuYLr4mO/vMx8flXhz6
gY/Eq0FVJKeF9s8HW/KbB92B4Cl2zIVWMQ==
-----END EC PRIVATE TEST KEY-----
`.replace(/TEST KEY/g, "KEY");

export const TEST_TLS_CLIENT_CERT = `
-----BEGIN TEST CERTIFICATE-----
MIIBrDCCAVGgAwIBAgIUaFUtmGfYMOnxHw1z70jp7FQUCNYwCgYIKoZIzj0EAwIw
FTETMBEGA1UEAwwKZGVtZXJnaTpDQTAgFw02OTEyMzEyMzAwMDBaGA8yOTY5MDUw
MjIzMDAwMFowGTEXMBUGA1UEAwwOZGVtZXJnaTpDbGllbnQwWTATBgcqhkjOPQIB
BggqhkjOPQMBBwNCAAQzPTZwKD+2UcjVA/YzvchD1po0sDeHGepgy5guviY7+8zH
x+VeHPqBj8SrQVUkp4X2zwdb8psH3YHgKXbMhVYxo3kwdzA1BgNVHREELjAsggdk
ZW1lcmdpgglsb2NhbGhvc3SHBH8AAAGHEAAAAAAAAAAAAAAAAAAAAAEwHQYDVR0O
BBYEFOHCT8tp6aTxFLTnqHlDMDjiAT0+MB8GA1UdIwQYMBaAFD6BmF0nSWUIKZRK
j9c02ygHMKeAMAoGCCqGSM49BAMCA0kAMEYCIQDY7yuEHB5dgjlRJl71bL3DHxt9
/Iw7jbUAOLLuFKxTswIhAK7pb+T5FdYMnC273uPq7KPev0BjuGpldN95RTO7wrBi
-----END TEST CERTIFICATE-----
`.replace(/TEST CERTIFICATE/g, "CERTIFICATE");

export const TEST_TLS_CLIENT_EXPIRED_CERT = `
-----BEGIN TEST CERTIFICATE-----
MIIBqTCCAU+gAwIBAgIUaFUtmGfYMOnxHw1z70jp7FQUCNgwCgYIKoZIzj0EAwIw
FTETMBEGA1UEAwwKZGVtZXJnaTpDQTAeFw02OTEyMzEyMzAwMDBaFw03MDAxMDEy
MzAwMDBaMBkxFzAVBgNVBAMMDmRlbWVyZ2k6Q2xpZW50MFkwEwYHKoZIzj0CAQYI
KoZIzj0DAQcDQgAEMz02cCg/tlHI1QP2M73IQ9aaNLA3hxnqYMuYLr4mO/vMx8fl
Xhz6gY/Eq0FVJKeF9s8HW/KbB92B4Cl2zIVWMaN5MHcwNQYDVR0RBC4wLIIHZGVt
ZXJnaYIJbG9jYWxob3N0hwR/AAABhxAAAAAAAAAAAAAAAAAAAAABMB0GA1UdDgQW
BBThwk/Laemk8RS056h5QzA44gE9PjAfBgNVHSMEGDAWgBQ+gZhdJ0llCCmUSo/X
NNsoBzCngDAKBggqhkjOPQQDAgNIADBFAiB6WWe4SzgclnTrUmCYMjB38wrub8m1
DF9bxdz7fHYWugIhAP1c3IvmMu/YPPIHPHexeVx2RXfKjyw7+CDPwZvh4mKn
-----END TEST CERTIFICATE-----
`.replace(/TEST CERTIFICATE/g, "CERTIFICATE");

export const TEST_TLS_CLIENT_INVALID_CERT = `
-----BEGIN TEST CERTIFICATE-----
MIIBqzCCAVGgAwIBAgIUB0Vkwh5/MjFsZbJ7o94fYBRaeOgwCgYIKoZIzj0EAwIw
FTETMBEGA1UEAwwKZGVtZXJnaTpDQTAgFw02OTEyMzEyMzAwMDBaGA8yOTY5MDUw
MjIzMDAwMFowGTEXMBUGA1UEAwwOZGVtZXJnaTpDbGllbnQwWTATBgcqhkjOPQIB
BggqhkjOPQMBBwNCAAQCvjtELR/2LzrD/DHdaJcD7Fzu/b/TwCy5Z/bau3F2kH8I
dxYCFm1jqWlFvFa+icfthQ/0ZyCPdtOzXYE9eSWWo3kwdzA1BgNVHREELjAsggdk
ZW1lcmdpgglsb2NhbGhvc3SHBH8AAAGHEAAAAAAAAAAAAAAAAAAAAAEwHQYDVR0O
BBYEFKipJjb0eBFUPLeQOnbkfq0Cn9UBMB8GA1UdIwQYMBaAFAXDewnOPHuTkEcy
yWBztSM8qzZuMAoGCCqGSM49BAMCA0gAMEUCICCIeUIH4TXMseUDfi4e26U5LByl
7SZDS+2BDQGgs3HZAiEA2l3lifh+VPlDk3g1/H8BVdVzjNzs1n7lbGUad3oPP8o=
-----END TEST CERTIFICATE-----
`.replace(/TEST CERTIFICATE/g, "CERTIFICATE");

export const TEST_TLS_MALFORMED_KEY = `
-----BEGIN EC PARAMETERS-----
xxxxxxxxxxxxxxxx
-----END EC PARAMETERS-----
-----BEGIN EC PRIVATE TEST KEY-----
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
-----END EC PRIVATE TEST KEY-----
`.replace(/TEST KEY/g, "KEY");

export const TEST_TLS_MALFORMED_CERT = `
-----BEGIN TEST CERTIFICATE-----
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
-----END TEST CERTIFICATE-----
`.replace(/TEST CERTIFICATE/g, "CERTIFICATE");
