name: 'CI'

on:
  push:
    tags: ['*']
    branches: ['*']
  pull_request:
    branches: ['*']
  schedule:
    - cron: '25 12 * * 3'

jobs:

  build-node:
    name: 'Node.js ${{matrix.node_version}} on ${{matrix.os}}'
    runs-on: '${{matrix.os}}'
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        node_version: ['14', '16', '17']
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2'
      - name: 'Use Node.js ${{matrix.node_version}}'
        uses: 'actions/setup-node@v2'
        with:
          node-version: '${{matrix.node_version}}'
          cache: 'npm'
      - name: 'Install'
        run: 'npm ci'
      - name: 'Lint'
        run: 'npm run lint'
      - name: 'Test'
        run: 'npm run test'
      - name: 'Build'
        run: 'npm run build-bundle'

  build-docker:
    name: 'Docker'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2'
      - name: 'Set up QEMU'
        uses: 'docker/setup-qemu-action@v1'
      - name: 'Set up Docker Buildx'
        uses: 'docker/setup-buildx-action@v1'
      - name: 'Login to GitHub Container Registry'
        if: "github.event_name != 'pull_request'"
        uses: 'docker/login-action@v1'
        with:
          registry: 'ghcr.io'
          username: '${{ github.actor }}'
          password: '${{ secrets.GITHUB_TOKEN }}'
      - name: 'Login to Docker Hub'
        if: "github.event_name != 'pull_request'"
        uses: 'docker/login-action@v1'
        with:
          registry: 'docker.io'
          username: '${{ secrets.DOCKERHUB_USERNAME }}'
          password: '${{ secrets.DOCKERHUB_TOKEN }}'
      - name: 'Extract metadata'
        id: 'meta'
        uses: 'docker/metadata-action@v3'
        with:
          images: |
            ghcr.io/hectorm/demergi
            docker.io/hectormolinero/demergi
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: 'Build and push'
        uses: 'docker/build-push-action@v2'
        with:
          context: './'
          platforms: 'linux/amd64,linux/arm64'
          tags: '${{ steps.meta.outputs.tags }}'
          labels: '${{ steps.meta.outputs.labels }}'
          push: "${{ github.event_name != 'pull_request' }}"
