name: 'CI'

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:

  build:
    name: 'Node.js ${{matrix.node_version}} on ${{matrix.os}}'
    runs-on: '${{matrix.os}}'
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        node_version: ['14', '16', '17']
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2'
      - name: 'Use Node.js ${{matrix.node_version}}'
        uses: 'actions/setup-node@v2'
        with:
          node-version: '${{matrix.node_version}}'
          cache: 'npm'
      - name: 'Install'
        run: 'npm ci'
      - name: 'Lint'
        run: 'npm run lint'
      - name: 'Test'
        run: 'npm run test'
