name: 'Scorecard security analysis'

on:
  push:
    branches: ['master']
  schedule:
    - cron: '25 10 * * 3'
  workflow_dispatch:

permissions: {}

jobs:

  analyze:
    name: 'Scorecard security analysis'
    runs-on: 'ubuntu-latest'
    permissions:
      actions: 'read'
      contents: 'read'
      security-events: 'write'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3'
      - name: 'Perform security analysis'
        uses: 'ossf/scorecard-action@80e868c13c90f172d68d1f4501dee99e2479f7af'
        with:
          results_file: './results.sarif'
          results_format: 'sarif'
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          publish_results: false
      - name: 'Upload SARIF file'
        uses: 'github/codeql-action/upload-sarif@04df1262e6247151b5ac09cd2c303ac36ad3f62b'
        with:
          sarif_file: './results.sarif'
