name: 'Scorecard security analysis'

on:
  push:
    branches: ['master']
  schedule:
    - cron: '25 10 * * 3'
  workflow_dispatch:

permissions: {}

jobs:

  analyze:
    name: 'Scorecard security analysis'
    runs-on: 'ubuntu-latest'
    permissions:
      actions: 'read'
      contents: 'read'
      security-events: 'write'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b'
      - name: 'Perform security analysis'
        uses: 'ossf/scorecard-action@ce330fde6b1a5c9c75b417e7efc510b822a35564'
        with:
          results_file: './results.sarif'
          results_format: 'sarif'
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          publish_results: false
      - name: 'Upload SARIF file'
        uses: 'github/codeql-action/upload-sarif@c7f292ea4f542c473194b33813ccd4c207a6c725'
        with:
          sarif_file: './results.sarif'
